<a href="https://colab.research.google.com/github/unt-iialab/INFO5731_Spring2020/blob/master/In_class_exercise/In_class_exercise_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **The second In-class-exercise (9/9/2020, 20 points in total)**

(1) Write a Python program to find the duplicate elements in a given array of integers. Return -1 If there are no such elements. (4 points)

In [ ]:
# write your answer here
arr_elems_Comn = [ ]
elements = input("Enter array elements\t").split(',') # taking array elements from user
arr1_Int = [int (i) for i in elements] #converting string elements into integer
for i in range(0,len(arr1_Int)):
  for j in range(i+1,len(arr1_Int)):
    if arr1_Int[i] == arr1_Int[j]:
      arr_elems_Comn.append(arr1_Int[j])
print("elements common in array is: {}".format(arr_elems_Comn))
if (sum(arr_elems_Comn) == 0):
  print(-1)

Enter array elements	1,1
elements common in array is: [1]

(2) Write a Python program to select all the Sundays of a specified year. (4 points)

In [ ]:
# write your answer here
# import datetime as dt
# x = dt.datetime.now()
# print(x.month)
# print(x.strftime("%A"))
# def date(x):
import datetime as dt 
import pandas as pd
All_Dates = [ ]
All_Months = [ ]
All_Sunday = [ ]
All_Year = [ ]
year = int (input("enter year:\t"))
O = dt.date(year, 1, 1)
O = O + dt.timedelta(days= 6 - O.weekday())
while (O.year == year):
    All_Months.append(O.strftime("%B"))
    All_Dates.append(O)
    All_Sunday.append(O.strftime("%A"))
    All_Year.append(O.year)
    O = O + dt.timedelta(days=7)
columns = ['date','year','month','day']
df = pd.DataFrame({'Date':All_Dates,'Month': All_Months,'Day':All_Sunday,'Year': All_Year})
df

enter year:	2021

          Date      Month     Day  Year
0   2021-01-03    January  Sunday  2021
1   2021-01-10    January  Sunday  2021
2   2021-01-17    January  Sunday  2021
3   2021-01-24    January  Sunday  2021
4   2021-01-31    January  Sunday  2021
5   2021-02-07   February  Sunday  2021
6   2021-02-14   February  Sunday  2021
7   2021-02-21   February  Sunday  2021
8   2021-02-28   February  Sunday  2021
9   2021-03-07      March  Sunday  2021
10  2021-03-14      March  Sunday  2021
11  2021-03-21      March  Sunday  2021
12  2021-03-28      March  Sunday  2021
13  2021-04-04      April  Sunday  2021
14  2021-04-11      April  Sunday  2021
15  2021-04-18      April  Sunday  2021
16  2021-04-25      April  Sunday  2021
17  2021-05-02        May  Sunday  2021
18  2021-05-09        May  Sunday  2021
19  2021-05-16        May  Sunday  2021
20  2021-05-23        May  Sunday  2021
21  2021-05-30        May  Sunday  2021
22  2021-06-06       June  Sunday  2021
23  2021-06-13       June  Sunday  2021
24  2021-06-20       June  Sunday  2021
25  2021-06-27       June  Sunday  2021
26  2021-07-04       July  Sunday  2021
27  2021-07-11       July  Sunday  2021
28  2021-07-18       July  Sunday  2021
29  2021-07-25       July  Sunday  2021
30  2021-08-01     August  Sunday  2021
31  2021-08-08     August  Sunday  2021
32  2021-08-15     August  Sunday  2021
33  2021-08-22     August  Sunday  2021
34  2021-08-29     August  Sunday  2021
35  2021-09-05  September  Sunday  2021
36  2021-09-12  September  Sunday  2021
37  2021-09-19  September  Sunday  2021
38  2021-09-26  September  Sunday  2021
39  2021-10-03    October  Sunday  2021
40  2021-10-10    October  Sunday  2021
41  2021-10-17    October  Sunday  2021
42  2021-10-24    October  Sunday  2021
43  2021-10-31    October  Sunday  2021
44  2021-11-07   November  Sunday  2021
45  2021-11-14   November  Sunday  2021
46  2021-11-21   November  Sunday  2021
47  2021-11-28   November  Sunday  2021
48  2021-12-05   December  Sunday  2021
49  2021-12-12   December  Sunday  2021
50  2021-12-19   December  Sunday  2021
51  2021-12-26   December  Sunday  2021

(3) Python files reading and writing. Download the “[exercise_02_data _collection.zip](https://github.com/unt-iialab/INFO5731_FALL2020/blob/master/In_class_exercise/exercise_02_data_collection.zip)” to your local and un-zip it.

*   Write a program to read all the txt files and save the sentences in all the files into one csv file with two columns, the first column is sentence id (txt file name+sentence line number), the second column is the sentence text content. (4 points)
*   Remove all the punctuations from the sentences, save the processed sentences into a new column in the same csv file. (4 points)
*   Ask the user to enter a word, return all the sentences that include this word, three kinds of information should be returned: sentence id, sentence text content, the count that user input word appear in the sentence. (4 points)

In [ ]:
import pandas as pd
import numpy as np
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
# write your answer here
#Q1
fileName = ['ARTHROTEC.1.txt','ARTHROTEC.1.txt','ARTHROTEC.1.txt','ARTHROTEC.1.txt','ARTHROTEC.1.txt' ]
index = []
df = pd.read_csv("/content/ARTHROTEC.1.txt",delimiter = '\t',names={'Sentences'})
for i in range(2,101):
 df1 = pd.read_csv("/content/ARTHROTEC."+str (i)+".txt",delimiter = '\t',names={'Sentences'})
 for j in range(len(df1)):
   fileName.append("ARTHROTEC."+str (i)+".txt")
 df = df.append(df1)
for i in range(1,len(df)+1):
   index.append(str (i))
df['filename'] = fileName
df['Index'] = index
df['Index_Files'] = df['filename']+" "+df['Index']
df = df.drop(columns = ["filename","Index"])
# Q2
df["Sente_without_Punc"] = df['Sentences'].str.replace('[^\w\s]','')
df = df.drop(columns="Sentences")
df.to_csv("ARTHROTEC.csv", index= False)
#Q3
word_Appear = 0
j = 0
df_Word = pd.read_csv("/content/ARTHROTEC.csv")
df_Orginal = df_Word.copy()
word = input("enter a word here:\t")
df_Word['Sente_without_Punc_Tokenized'] = df_Word.apply(lambda row: nltk.word_tokenize(str (row['Sente_without_Punc'])), axis=1)
for i in range(len(df_Word)):
  k = df_Word['Sente_without_Punc_Tokenized'][i]
  for j in range(len(k)):
   if any(word == k[j]):
      df_Orginal[i]         
# k =   df_Word['Sente_without_Punc_Tokenized'][0]  
# len(k)             

# df_Word['Sente_without_Punc_Tokenized'][0]
# str (df['Sente_without_Punc'][0])
  #  if word in a:
  #      print("{},{}",df["fileName"][i],df["Sente_without_Punc"][i])
  #     while word in a:
  #       for i in range(0,df["Sente_without_Punc"][i].str.len()):

          # print(df["Sente_without_Punc"][i].count(word))

#    if (word == df['Sente_without_Punc_tokenized'][i][j]):
#      word_Appear +=1
#      print(df["fileName"][i] +""+ df["Sente_without_Punc"])
# len(df['Sente_without_Punc_tokenized'][0])
# len(df['Sente_without_Punc_tokenized'][0][0])
#  a = [i for i in range()]
#      word_Appear +=1
# print(df["fileName"][i] +""+ df["Sente_without_Punc"]+""+ word_Appear)
# df["Sente_without_Punc"][0].str.len()

enter a word here:	feel

TypeError: ignored

(4) Install packages nltk, numpy, scipy, pandas, and sklearn on Google Colab. Write a program to test whether they are installed successfully. (3 points for extra)

In [ ]:
# write your answer here